SELECT 		C.TGL_DAFTAR, 
			C.NO_PENDAFTARAN, 
			C.NORM, 
			F.NAMA, 
			A.NM_INST, 
			B.NM_POLI, 
			D.JNS_CARABAYAR, 
			H.KD_ICD, 
			H.NM_ICD, 
			I.NM_JNS_DIAGNOSA, 
			C.STS_BATAL
	FROM 	MDFT_INSTALASI A,
			MDFT_POLI_SMF B,
			TDFT_PENDAFTARAN C,
			MMAS_JNS_CRBYR D,
			TDFT_CRBYR_PASIEN1 E,
			TDFT_PASIEN_RM F,
			TRM_DIAGNOSA_PSN G,
			MMAS_RM_ICD H,
			MMAS_JNS_DIAGNOSA I
	WHERE	A.KD_INST  			= B.KD_INST  AND
			B.KD_INST  			= C.KD_INST  AND
			B.KD_POLI  			= C.KD_POLI  AND
			C.NO_PENDAFTARAN   	= E.NO_PENDAFTARAN AND
			D.KD_BAYAR         	= E.KD_BAYAR AND
			D.KD_JNS_CARABAYAR 	= E.KD_JNS_CARABAYAR AND
			C.NORM             	= F.NORM AND
			G.NO_PENDAFTARAN   	= C.NO_PENDAFTARAN AND
			G.KD_ICD           	= H.KD_ICD AND
			G.KD_JNS_DIAGNOSA  	= I.KD_JNS_DIAGNOSA AND 
			--G.KD_JNS_DIAGNOSA  = '00' AND
			C.TGL_DAFTAR >= '2022/01/01' AND C.TGL_DAFTAR < '2022/04/01' AND
			-- A.KD_KLP     = '01' AND
			A.KD_INST  IN ('01','03','13','14','39','40','46')  and
			---D.KD_BAYAR = '001' AND
			C.STS_PASIEN <> '9' AND
			--C.STS_BATAL <> '1'
			-- B.KD_POLI     = '01' AND
			(C.STS_BATAL IS NULL OR C.STS_BATAL = '0') and
			H.KD_ICD IN ('U07.1','U07.2','A30.9','A36.8','A36.9','B20','B20.0','B20.1','B20.2','B20.3','B20.4','B20.5','B20.6','B20.7','B20.8','B20.9','A90','A91','A91.0','A91.1','A91.9 ')
			--- C.NO_PENDAFTARAN = '201406072756'
	ORDER 	BY B.NM_POLI ASC