DROP FUNCTION IF EXISTS rsfMaster.getTrfTindNonKelas;
DELIMITER $$
CREATE DEFINER=`root`@`localhost` FUNCTION `rsfMaster`.`getTrfTindNonKelas`(
	`PTINDAKAN` SMALLINT,
	`PTANGGAL` DATETIME
) RETURNS int(11)
    DETERMINISTIC
BEGIN 
	DECLARE VTARIF INT;
	SELECT TARIF INTO VTARIF
	  FROM master.tarif_tindakan
	 WHERE TINDAKAN = PTINDAKAN
	   AND TANGGAL_SK <= PTANGGAL
		AND KELAS != 17
		AND KELAS != 18
	 ORDER BY TANGGAL DESC LIMIT 1;
	
	IF FOUND_ROWS() = 0 THEN 
		SELECT TARIF INTO VTARIF 
		  FROM master.tarif_tindakan
		 WHERE TINDAKAN = PTINDAKAN
		   AND STATUS = 1
		   AND KELAS != 17
		   AND KELAS != 18
		 ORDER BY TANGGAL DESC LIMIT 1;	
		 
		IF FOUND_ROWS() = 0 THEN
			SET VTARIF = 0;
		END IF;
	END IF;

	RETURN VTARIF;
END$$
DELIMITER ;
