CREATE DEFINER=`root`@`127.0.0.1` TRIGGER `onAfterInsertTujuanPasien` AFTER INSERT ON `tujuan_pasien` FOR EACH ROW BEGIN
	DECLARE VIDANTRIAN MEDIUMINT;
	DECLARE VTGL DATE;
	DECLARE VNOMORANTRIANPOLI INT(30);
	
	IF NEW.RESERVASI != 'HOSPIA' THEN
		INSERT INTO pendaftaran.antrian_ruangan(RUANGAN, JENIS, REF)
		VALUES(NEW.RUANGAN, 1, NEW.NOPEN);
	
		SELECT ID INTO VIDANTRIAN FROM aplikasi.properti_config WHERE ID = 90085 AND VALUE = 'TRUE';
		IF FOUND_ROWS() > 0 THEN
			SELECT date_format(TANGGAL,'%Y-%m-%d') INTO VTGL FROM pendaftaran.pendaftaran WHERE NOMOR = NEW.NOPEN;
			IF FOUND_ROWS() > 0 THEN
				SET VNOMORANTRIANPOLI = (SELECT regonline.generateNoAntrianPoli(NEW.RUANGAN, VTGL));
				INSERT INTO regonline.antrian_poli(ASAL_REF,REF,NOMOR,POLI,TANGGAL,STATUS) VALUES (2,NEW.NOPEN, VNOMORANTRIANPOLI, NEW.RUANGAN, VTGL,2);
			END IF;
		END IF;
	END IF;
END