DROP FUNCTION IF EXISTS rsfPegawai.getDTOcrbyr;
DELIMITER $$
CREATE FUNCTION rsfPegawai.getDTOcrbyr(
	PTYPE INTEGER,
	PRUANGDAFTAR CHAR(10),
	PRUANGLAYAN CHAR(10),
	PCARABAYARID INTEGER,
	PTINDAKAN BIGINT
) RETURNS VARCHAR(15) DETERMINISTIC
BEGIN 
	DECLARE VDTOCRBYR VARCHAR(15);
	DECLARE VKLPRUANG VARCHAR(15);
	DECLARE VCOUNT INTEGER;
	
	SET VKLPRUANG = '';
	IF (SUBSTRING(PRUANGDAFTAR,1,5) = '10127') THEN
		SET VDTOCRBYR = 'EXECUTIVE';
		IF (SUBSTRING(PRUANGLAYAN,1,5) = '10127') THEN
			SET VKLPRUANG = 'IGH.POLI';
		ELSEIF (SUBSTRING(PRUANGLAYAN,1,5) = '10108') THEN
			SET VKLPRUANG = 'IGH.RAD';
		ELSEIF (SUBSTRING(PRUANGLAYAN,1,5) = '10109') THEN
			SET VKLPRUANG = 'IGH.BOUG';
		ELSEIF (SUBSTRING(PRUANGLAYAN,1,7) = '1010701') THEN
			SET VKLPRUANG = 'IGH.LAB';
		ELSEIF (SUBSTRING(PRUANGLAYAN,1,7) = '1010701') THEN
			SET VKLPRUANG = 'IGH.PA';
		ELSEIF ((PRUANGLAYAN = '101180101') or (PRUANGLAYAN = '101170101')) THEN
			SET VKLPRUANG = 'IGH.UKVI';
		ELSE
			SET VKLPRUANG = 'IGH.LAIN';
		END IF;
		IF (PCARABAYARID = 2) THEN
			select 		count(1)
				into	VCOUNT
				from 	rsfPelaporan.tremun_kegiatan_klp 
				where 	kegiatan_id = PTINDAKAN and dto_kegiatan_klp = 'rawatjalan';
			IF (VCOUNT = 0) THEN
				SET VDTOCRBYR = 'JKN';
				SET VKLPRUANG = CONCAT(VKLPRUANG,'.TJKN');
			END IF;
		END IF;
	ELSEIF (PCARABAYARID = 7) THEN
		SET VDTOCRBYR = 'EXECUTIVE';
		SET VKLPRUANG = 'BEDAHPRIMA';
	ELSEIF (PCARABAYARID = 2) THEN
		SET VDTOCRBYR = 'JKN';
	ELSEIF ((PRUANGLAYAN = '101180101') or (PRUANGLAYAN = '101170101')) THEN
		SET VDTOCRBYR = 'EXECUTIVE';
		SET VKLPRUANG = 'UKVI.NJKN';
	ELSE
		SET VDTOCRBYR = 'REGULER';
	END IF;
	IF PTYPE = 1 THEN
		RETURN VDTOCRBYR;
	ELSE
		RETURN VKLPRUANG;
	END IF;
END$$
DELIMITER ;
