SELECT		TBIL_PENDAFTARAN.NO_PENDAFTARAN  as NO_PENDAFTARAN,
			TBIL_PENDAFTARAN.TGL_DAFTAR as TGL_DAFTAR,
			TBIL_PENDAFTARAN.NORM as NORM,
			TBIL_PENDAFTARAN.NAMA as NAMA,
			MMAS_CARABAYAR.KD_BAYAR as KD_BAYAR,
			TBIL_PENDAFTARAN.KLP_BYR as KLP_BAYAR,
			MMAS_CARABAYAR.CARABAYAR as CRBYR,
			MMAS_JNS_CRBYR.JNS_CARABAYAR as JNS_CARABAYAR,
			isnull((MDFT_RRAWAT.NM_RRAWAT),'IRD') as RRAWAT,
			TBIL_TAGIHAN.HB_BA + TBIL_TAGIHAN.HB_RS + TBIL_TAGIHAN.HB_LYN as BIAYA,
			MDFT_INSTALASI.NM_INST as NM_INST,
			TDFT_SRTJLN.NO_SRTJLN as NO_SRTJLN,
			TDFT_SRTJLN.NO_KENDARAAN as NO_KENDARAAN,
			TDFT_SRTJLN.TUJUAN as TUJUAN,
			TDFT_SRTJLN.ZONA as ZONA,
			MMAS_AMB_PERAWAT.NM_PERAWAT as PERAWAT,
			MMAS_AMB_PETUGAS.NM_PETUGAS as PETUGAS,
			MMAS_AMB_KEPERLUAN.NM_KEPERLUAN as KEPERLUAN
	FROM  	TBIL_TAGIHAN,
			TDFT_PENDAFTARAN,
			TBIL_PENDAFTARAN
			left outer join TDFT_RJK_MASUK on TDFT_RJK_MASUK.NO_PENDAFTARAN = TBIL_PENDAFTARAN.NO_PENDAFTARAN
			left outer join MDFT_RRAWAT on TDFT_RJK_MASUK.KD_RRAWAT         = MDFT_RRAWAT.KD_RRAWAT
			left outer join TDFT_SRTJLN on TDFT_SRTJLN.NO_PENDAFTARAN       = TBIL_PENDAFTARAN.NO_PENDAFTARAN
			left outer join MMAS_AMB_PERAWAT on TDFT_SRTJLN.KD_PERAWAT      = MMAS_AMB_PERAWAT.KD_PERAWAT
			left outer join MMAS_AMB_PETUGAS on TDFT_SRTJLN.KD_PETUGAS      = MMAS_AMB_PETUGAS.KD_PETUGAS
			left outer join MMAS_AMB_KEPERLUAN on TDFT_SRTJLN.KD_KEPERLUAN  = MMAS_AMB_KEPERLUAN.KD_KEPERLUAN,
			MMAS_CARABAYAR,
			MMAS_JNS_CRBYR,
			MDFT_INSTALASI
	WHERE 	TBIL_TAGIHAN.NO_PENDAFTARAN         = TBIL_PENDAFTARAN.NO_PENDAFTARAN AND       
			TDFT_PENDAFTARAN.NO_PENDAFTARAN     = TBIL_PENDAFTARAN.NO_PENDAFTARAN AND
			TBIL_PENDAFTARAN.KD_BAYAR           = MMAS_CARABAYAR.KD_BAYAR AND
			TBIL_PENDAFTARAN.KD_BAYAR           = MMAS_JNS_CRBYR.KD_BAYAR AND
			TBIL_PENDAFTARAN.KD_JNS_CARABAYAR   = MMAS_JNS_CRBYR.KD_JNS_CARABAYAR AND
			TBIL_PENDAFTARAN.TGL_DAFTAR        >= '2023-02-28' AND
			TBIL_PENDAFTARAN.TGL_DAFTAR         < dateadd( DAY, 1, '2023-02-28' ) AND
			isnull(TDFT_PENDAFTARAN.STS_BATAL,'0') = '0' and
			TBIL_PENDAFTARAN.KD_INST            = '32' AND
			TBIL_PENDAFTARAN.KD_INST            = MDFT_INSTALASI.KD_INST
