SELECT   	MDFT_ASAL_RUJUKAN.NM_ASAL_RJK as RUJUKAN,
			MDFT_ASAL_RUJUKAN.KD_ASAL_RJK,
			sum(1) as TOTAL,
			sum(charindex('01',MMAS_JNS_CRBYR.KD_KLP_CRBYR)) as KLP_01,
			sum(charindex('02',MMAS_JNS_CRBYR.KD_KLP_CRBYR)) as KLP_02,
			sum(charindex('03',MMAS_JNS_CRBYR.KD_KLP_CRBYR)) as KLP_03,
			sum(charindex('04',MMAS_JNS_CRBYR.KD_KLP_CRBYR)) as KLP_04,
			sum(charindex('05',MMAS_JNS_CRBYR.KD_KLP_CRBYR)) as KLP_05,
			sum(charindex('06',MMAS_JNS_CRBYR.KD_KLP_CRBYR)) as KLP_06,
			sum(charindex('07',MMAS_JNS_CRBYR.KD_KLP_CRBYR)) as KLP_07,
			sum(charindex('08',MMAS_JNS_CRBYR.KD_KLP_CRBYR)) as KLP_08,
			sum(charindex('09',MMAS_JNS_CRBYR.KD_KLP_CRBYR)) as KLP_09,
			sum(charindex('10',MMAS_JNS_CRBYR.KD_KLP_CRBYR)) as KLP_10,
			sum(charindex('11',MMAS_JNS_CRBYR.KD_KLP_CRBYR)) as KLP_11,
			sum(charindex('12',MMAS_JNS_CRBYR.KD_KLP_CRBYR)) as KLP_12,
			sum(charindex('13',MMAS_JNS_CRBYR.KD_KLP_CRBYR)) as KLP_13
	FROM    MDFT_ASAL_RUJUKAN,
			TDFT_PENDAFTARAN
			left outer join TDFT_RJK_MASUK on TDFT_PENDAFTARAN.NO_PENDAFTARAN = TDFT_RJK_MASUK.NO_PENDAFTARAN
			left outer join TDFT_CRBYR_PASIEN1 on TDFT_PENDAFTARAN.NO_PENDAFTARAN = TDFT_CRBYR_PASIEN1.NO_PENDAFTARAN
			left outer join MMAS_JNS_CRBYR on TDFT_CRBYR_PASIEN1.KD_BAYAR = MMAS_JNS_CRBYR.KD_BAYAR  and
													TDFT_CRBYR_PASIEN1.KD_JNS_CARABAYAR	= MMAS_JNS_CRBYR.KD_JNS_CARABAYAR
	WHERE   TDFT_PENDAFTARAN.KD_ASAL_RJK = MDFT_ASAL_RUJUKAN.KD_ASAL_RJK and
			( TDFT_PENDAFTARAN.KD_INST = '14' AND
			TDFT_PENDAFTARAN.STS_PASIEN <> '9' AND
			TDFT_PENDAFTARAN.TGL_DAFTAR >= '2023-02-28' AND
			TDFT_PENDAFTARAN.TGL_DAFTAR <  dateadd(day,1,'2023-02-28') )
	GROUP 	BY  MDFT_ASAL_RUJUKAN.NM_ASAL_RJK,
				MDFT_ASAL_RUJUKAN.KD_ASAL_RJK
