update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '000559' and sakti_nama_klp = 'OBAT PADAT (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '001036' and sakti_nama_klp = 'ALAT/ OBAT KONTRASEPSI KELUARGA BERENCANA(PERSEDIAAN  LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '001100' and sakti_nama_klp = 'ALAT/ OBAT KONTRASEPSI KELUARGA BERENCANA(PERSEDIAAN  LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '001039' and sakti_nama_klp = 'ALAT/ OBAT KONTRASEPSI KELUARGA BERENCANA(PERSEDIAAN  LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '001037' and sakti_nama_klp = 'ALAT/ OBAT KONTRASEPSI KELUARGA BERENCANA(PERSEDIAAN  LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '001056' and sakti_nama_klp = 'ALAT/ OBAT KONTRASEPSI KELUARGA BERENCANA(PERSEDIAAN  LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '001088' and sakti_nama_klp = 'ALAT/ OBAT KONTRASEPSI KELUARGA BERENCANA(PERSEDIAAN  LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '001089' and sakti_nama_klp = 'ALAT/ OBAT KONTRASEPSI KELUARGA BERENCANA(PERSEDIAAN  LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '001090' and sakti_nama_klp = 'ALAT/ OBAT KONTRASEPSI KELUARGA BERENCANA(PERSEDIAAN  LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '001091' and sakti_nama_klp = 'ALAT/ OBAT KONTRASEPSI KELUARGA BERENCANA(PERSEDIAAN  LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '001092' and sakti_nama_klp = 'ALAT/ OBAT KONTRASEPSI KELUARGA BERENCANA(PERSEDIAAN  LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '001095' and sakti_nama_klp = 'ALAT/ OBAT KONTRASEPSI KELUARGA BERENCANA(PERSEDIAAN  LAINNYA)';

update tjurnal_sakti set katalog_kode_baru = 'PFA048', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '000741' and sakti_nama_klp = 'OBAT CAIR (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '40A128', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '003303' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '40A111', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '000141' and sakti_nama_klp = 'OBAT CAIR (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '001821' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '42A129', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '004166' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '18A017.01', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '004200' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '000572' and sakti_nama_klp = 'OBAT PADAT (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '000469' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '001138' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '000435' and sakti_nama_klp = 'OBAT PADAT (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '000130' and sakti_nama_klp = 'OBAT PADAT (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '80B120.1', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '001457' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '81B185', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '004140' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '30F004', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '000110' and sakti_nama_klp = 'OBAT GEL/SALEP (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '42C1000.04', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '003072' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '42C028', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '004174' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '42C841', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '004175' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '80C045', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '004191' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '80C096', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '002893' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '70C034', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '000187' and sakti_nama_klp = 'OBAT CAIR (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '22C024', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '004103' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '22C117', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '000140' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '22C117', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '004089' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '22C023', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '004104' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '10C098', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '000544' and sakti_nama_klp = 'OBAT PADAT (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '50C014', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '000038' and sakti_nama_klp = 'OBAT SERBUK/TEPUNG (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '40C037', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '000599' and sakti_nama_klp = 'OBAT CAIR (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '80C001.082', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '000816' and sakti_nama_klp = 'ALAT/ OBAT KONTRASEPSI KELUARGA BERENCANA(PERSEDIAAN  LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '42H076', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '001863' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '42C1000.38', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '001198' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '22C010', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '004196' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '42C094', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '000918' and sakti_nama_klp = 'ALAT/ OBAT KONTRASEPSI KELUARGA BERENCANA(PERSEDIAAN  LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '42C1000.22', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '003066' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '42C1000.02', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '003073' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '000462' and sakti_nama_klp = 'OBAT CAIR (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = 'PFD001', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '000046' and sakti_nama_klp = 'OBAT SERBUK/TEPUNG (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '80D123', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '002887' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '10D158.14204', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '000393' and sakti_nama_klp = 'OBAT PADAT (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '40D037', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '000033' and sakti_nama_klp = 'OBAT SERBUK/TEPUNG (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '80D152', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '001262' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '42D191', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '003651' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '42D197', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '001877' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '42D181', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '003055' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';

update tjurnal_sakti set katalog_kode_baru = '10D089', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '000505' and sakti_nama_klp = 'OBAT PADAT (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '90E008', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '002525' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '16E014', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '003790' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '80E016', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '004005' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '80E058', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '004008' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '10F043', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '000557' and sakti_nama_klp = 'OBAT PADAT (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '80F137', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '003573' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';

update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '002191' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '16F007', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '002126' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '42F111.01', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '001173' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '000014' and sakti_nama_klp = 'OBAT GAS (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '22G001', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '003169' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '16H002', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '003870' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '16H007', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '003871' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '16H008', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '003872' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '16H009', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '003873' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';

update tjurnal_sakti set katalog_kode_baru = '12H010', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '000018' and sakti_nama_klp = 'OBAT CAIR (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '80H140', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '004137' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '42H078', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '003038' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '80H139', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '002817' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';

update tjurnal_sakti set katalog_kode_baru = '17H001', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '003336' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '15I027', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '000951' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '15I041', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '002404' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '15I041.1', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '002403' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '000043' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '20I021', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '000016' and sakti_nama_klp = 'OBAT CAIR (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '42I073', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '004222' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '42I067', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '003685' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '15I102', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '002390' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '16K023', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '003800' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '16K025', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '003874' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '16K006', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '003818' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '16K034', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '003801' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '16K009.1', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '004016' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '16K011', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '003819' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '000758' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '90K055', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '002508' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '90K057', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '001591' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '15K154', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '002321' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '80K104', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '003926' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '30K021', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '000124' and sakti_nama_klp = 'OBAT GEL/SALEP (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '10K133', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '000664' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '14K004', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '001667' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '42K085', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '003031' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '42K107', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '001239' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '20L002', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '000656' and sakti_nama_klp = 'OBAT CAIR (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '42L759', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '003015' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '90L017', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '003824' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';

update tjurnal_sakti set katalog_kode_baru = '80L100.1', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '004003' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';





update tjurnal_sakti set katalog_kode_baru = '42L769.1', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '003849' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '42L765.01', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '003938' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '42L782', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '001109' and sakti_nama_klp = 'ALAT/ OBAT KONTRASEPSI KELUARGA BERENCANA(PERSEDIAAN  LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '42L743', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '000458' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '42L655', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '004231' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '42L764.03', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '001077' and sakti_nama_klp = 'ALAT/ OBAT KONTRASEPSI KELUARGA BERENCANA(PERSEDIAAN  LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '42l764.02', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '000119' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '42 003', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '004159' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '42L719', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '003026' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '42L727', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '003024' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '42L636', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '000104' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '42L637', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '000103' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '42L639', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '000102' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '80L095.1', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '000696' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '42M013', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '000891' and sakti_nama_klp = 'ALAT/ OBAT KONTRASEPSI KELUARGA BERENCANA(PERSEDIAAN  LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '10M031', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '000304' and sakti_nama_klp = 'OBAT PADAT (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '40M084', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '003251' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '42M320', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '003002' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '42M311', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '003009' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';

update tjurnal_sakti set katalog_kode_baru = '80N143', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '000537' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '80N144', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '000301' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';

update tjurnal_sakti set katalog_kode_baru = '80N152', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '004241' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';

update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '000578' and sakti_nama_klp = 'OBAT CAIR (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '000577' and sakti_nama_klp = 'OBAT CAIR (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '000588' and sakti_nama_klp = 'OBAT CAIR (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '000606' and sakti_nama_klp = 'OBAT CAIR (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '000607' and sakti_nama_klp = 'OBAT CAIR (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '000618' and sakti_nama_klp = 'OBAT CAIR (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '000608' and sakti_nama_klp = 'OBAT CAIR (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '000609' and sakti_nama_klp = 'OBAT CAIR (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '000610' and sakti_nama_klp = 'OBAT CAIR (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '000611' and sakti_nama_klp = 'OBAT CAIR (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '000015' and sakti_nama_klp = 'OBAT GAS (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '000016' and sakti_nama_klp = 'OBAT GAS (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '000017' and sakti_nama_klp = 'OBAT GAS (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '000018' and sakti_nama_klp = 'OBAT GAS (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '000019' and sakti_nama_klp = 'OBAT GAS (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '000020' and sakti_nama_klp = 'OBAT GAS (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '000021' and sakti_nama_klp = 'OBAT GAS (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '000098' and sakti_nama_klp = 'OBAT GEL/SALEP (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '000103' and sakti_nama_klp = 'OBAT GEL/SALEP (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '000104' and sakti_nama_klp = 'OBAT GEL/SALEP (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '000105' and sakti_nama_klp = 'OBAT GEL/SALEP (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '000112' and sakti_nama_klp = 'OBAT GEL/SALEP (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '000109' and sakti_nama_klp = 'OBAT GEL/SALEP (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '000106' and sakti_nama_klp = 'OBAT GEL/SALEP (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '000107' and sakti_nama_klp = 'OBAT GEL/SALEP (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '000111' and sakti_nama_klp = 'OBAT GEL/SALEP (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '003614' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '003572' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '003785' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '003920' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '003921' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '003980' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '003922' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '003923' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '003924' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '003955' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '000479' and sakti_nama_klp = 'OBAT PADAT (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '000485' and sakti_nama_klp = 'OBAT PADAT (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '000497' and sakti_nama_klp = 'OBAT PADAT (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '000498' and sakti_nama_klp = 'OBAT PADAT (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '000512' and sakti_nama_klp = 'OBAT PADAT (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '000499' and sakti_nama_klp = 'OBAT PADAT (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '000500' and sakti_nama_klp = 'OBAT PADAT (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '000501' and sakti_nama_klp = 'OBAT PADAT (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '000506' and sakti_nama_klp = 'OBAT PADAT (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '000025' and sakti_nama_klp = 'OBAT SERBUK/TEPUNG (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '000026' and sakti_nama_klp = 'OBAT SERBUK/TEPUNG (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '000027' and sakti_nama_klp = 'OBAT SERBUK/TEPUNG (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '000028' and sakti_nama_klp = 'OBAT SERBUK/TEPUNG (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '000037' and sakti_nama_klp = 'OBAT SERBUK/TEPUNG (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '000029' and sakti_nama_klp = 'OBAT SERBUK/TEPUNG (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '000030' and sakti_nama_klp = 'OBAT SERBUK/TEPUNG (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '000031' and sakti_nama_klp = 'OBAT SERBUK/TEPUNG (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '000036' and sakti_nama_klp = 'OBAT SERBUK/TEPUNG (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '', katalog_kode_primer = 'X', katalog_kode_aksi = '' where sakti_kode = '000130' and sakti_nama_klp = 'ALAT/ OBAT KONTRASEPSI KELUARGA BERENCANA(PERSEDIAAN  LAINNYA)';

update tjurnal_sakti set katalog_kode_baru = '15O029', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '000648' and sakti_nama_klp = 'OBAT CAIR (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '81P167', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '001106' and sakti_nama_klp = 'ALAT/ OBAT KONTRASEPSI KELUARGA BERENCANA(PERSEDIAAN  LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '70P014', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '000236' and sakti_nama_klp = 'OBAT CAIR (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '22P001', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '004090' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '81P056', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '001668' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '10P041', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '000254' and sakti_nama_klp = 'OBAT PADAT (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '40P025', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '000680' and sakti_nama_klp = 'OBAT CAIR (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '42P372', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '001057' and sakti_nama_klp = 'ALAT/ OBAT KONTRASEPSI KELUARGA BERENCANA(PERSEDIAAN  LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '22P164', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '000248' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '90P095', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '001113' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '90P096', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '001112' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '90P092', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '002499' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '90P093', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '001438' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '90P094', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '002498' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '20P021', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '003960' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '81I012', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '002588' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '80P197', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '002715' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '81P129', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '002572' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '22P018', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '003932' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '22P154', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '002711' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '42P051', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '000490' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '42P363', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '002983' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '81R091', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '000691' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '42R270', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '002972' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '40R062', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '001656' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '14R006', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '000716' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '42R269', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '001871' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '80R072', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '002699' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '80R037', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '001036' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '42S301', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '002956' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '42S311', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '002953' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '80S058.9', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '001104' and sakti_nama_klp = 'ALAT/ OBAT KONTRASEPSI KELUARGA BERENCANA(PERSEDIAAN  LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '80S020', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '003994' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '50S037', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '000738' and sakti_nama_klp = 'OBAT CAIR (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '42S270', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '001628' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '80S042', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '000550' and sakti_nama_klp = 'ALAT/ OBAT KONTRASEPSI KELUARGA BERENCANA(PERSEDIAAN  LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '42S216', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '004293' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '80S276', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '002686' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '80S228', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '002688' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '22S002', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '004138' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '30S034', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '000047' and sakti_nama_klp = 'OBAT GEL/SALEP (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '80T086', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '003999' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';

update tjurnal_sakti set katalog_kode_baru = '30T010', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '000043' and sakti_nama_klp = 'OBAT GEL/SALEP (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '10T119', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '000563' and sakti_nama_klp = 'OBAT PADAT (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '42T274', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '002948' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '90T016', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '000416' and sakti_nama_klp = 'ALAT/ OBAT KONTRASEPSI KELUARGA BERENCANA(PERSEDIAAN  LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '81U041', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '001854' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '15V017', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '002256' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '17M002', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '000001' and sakti_nama_klp = 'BARANG PERSEDIAAN';
update tjurnal_sakti set katalog_kode_baru = '42V068', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '001130' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '40V005', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '000598' and sakti_nama_klp = 'OBAT CAIR (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '40V052', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '003219' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '15W006', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '001578' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
