update tjurnal_sakti set katalog_kode_baru = '42A072', katalog_kode_primer = 'P', katalog_kode_aksi = '' where sakti_kode = '000267' and sakti_nama_klp = 'ALAT/ OBAT KONTRASEPSI KELUARGA BERENCANA(PERSEDIAAN  LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '42A072', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '004095' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '15A100', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '002209' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '15A100', katalog_kode_primer = 'P', katalog_kode_aksi = '' where sakti_kode = '002469' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '10C001.8', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '000528' and sakti_nama_klp = 'OBAT CAIR (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '10C001.8', katalog_kode_primer = 'P', katalog_kode_aksi = '' where sakti_kode = '001165' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '80C001.132', katalog_kode_primer = 'P', katalog_kode_aksi = '' where sakti_kode = '002904' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '80C001.132', katalog_kode_primer = '', katalog_kode_aksi = 'K01' where sakti_kode = '004176' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '85C009', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '000004' and sakti_nama_klp = 'OBAT GAS (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '85C009', katalog_kode_primer = 'P', katalog_kode_aksi = '' where sakti_kode = '000013' and sakti_nama_klp = 'OBAT GAS (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '15D005', katalog_kode_primer = '', katalog_kode_aksi = 'K01' where sakti_kode = '002200' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '15D005', katalog_kode_primer = 'P', katalog_kode_aksi = '' where sakti_kode = '002443' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '40D100', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '000665' and sakti_nama_klp = 'OBAT CAIR (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '40D100', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '001372' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '40D100', katalog_kode_primer = 'P', katalog_kode_aksi = 'KM.400' where sakti_kode = '001685' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '15I166', katalog_kode_primer = 'P', katalog_kode_aksi = '' where sakti_kode = '000867' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '15I166', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '002378' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '80J021.4', katalog_kode_primer = 'P', katalog_kode_aksi = '' where sakti_kode = '000668' and sakti_nama_klp = 'ALAT/ OBAT KONTRASEPSI KELUARGA BERENCANA(PERSEDIAAN  LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '80J001.009', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '000682' and sakti_nama_klp = 'ALAT/ OBAT KONTRASEPSI KELUARGA BERENCANA(PERSEDIAAN  LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '80J001.024', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '000155' and sakti_nama_klp = 'ALAT/ OBAT KONTRASEPSI KELUARGA BERENCANA(PERSEDIAAN  LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '80J001.024', katalog_kode_primer = 'P', katalog_kode_aksi = '' where sakti_kode = '000678' and sakti_nama_klp = 'ALAT/ OBAT KONTRASEPSI KELUARGA BERENCANA(PERSEDIAAN  LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '85N008', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '000003' and sakti_nama_klp = 'OBAT GAS (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '85N008', katalog_kode_primer = 'P', katalog_kode_aksi = '' where sakti_kode = '000012' and sakti_nama_klp = 'OBAT GAS (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '85O008', katalog_kode_primer = 'P', katalog_kode_aksi = '' where sakti_kode = '000007' and sakti_nama_klp = 'OBAT GAS (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '85O008', katalog_kode_primer = '', katalog_kode_aksi = 'K01' where sakti_kode = '000010' and sakti_nama_klp = 'OBAT GAS (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '42O036.01', katalog_kode_primer = 'P', katalog_kode_aksi = '' where sakti_kode = '000994' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '42O036.01', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '003615' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '15P112', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '000018' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '15P112', katalog_kode_primer = 'P', katalog_kode_aksi = '' where sakti_kode = '001582' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '80S004', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '000473' and sakti_nama_klp = 'ALAT/ OBAT KONTRASEPSI KELUARGA BERENCANA(PERSEDIAAN  LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '80S004', katalog_kode_primer = 'P', katalog_kode_aksi = '' where sakti_kode = '004066' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '40R060.1', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '000070' and sakti_nama_klp = 'OBAT CAIR (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '40R060.1', katalog_kode_primer = 'P', katalog_kode_aksi = 'KM.282' where sakti_kode = '000127' and sakti_nama_klp = 'OBAT CAIR (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '40R065', katalog_kode_primer = '', katalog_kode_aksi = 'K01' where sakti_kode = '000601' and sakti_nama_klp = 'OBAT CAIR (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '40R065', katalog_kode_primer = 'P', katalog_kode_aksi = '' where sakti_kode = '001682' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '81S190', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '003914' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '81S190', katalog_kode_primer = 'P', katalog_kode_aksi = '' where sakti_kode = '004098' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '80S351', katalog_kode_primer = 'P', katalog_kode_aksi = '' where sakti_kode = '001072' and sakti_nama_klp = 'ALAT/ OBAT KONTRASEPSI KELUARGA BERENCANA(PERSEDIAAN  LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '80S351', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '003957' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '15S095', katalog_kode_primer = 'P', katalog_kode_aksi = '' where sakti_kode = '000371' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
update tjurnal_sakti set katalog_kode_baru = '15S095', katalog_kode_primer = '', katalog_kode_aksi = '' where sakti_kode = '001580' and sakti_nama_klp = 'OBAT LAINNYA (PERSEDIAAN LAINNYA)';
